/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteRouteImport } from './routes/test/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TestHomeRouteImport } from './routes/test/home'
import { Route as AdminSettingsRouteRouteImport } from './routes/admin/settings/route'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTransactionsIndexRouteImport } from './routes/admin/transactions/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminUsersRolesIndexRouteImport } from './routes/admin/users/roles/index'
import { Route as AdminSettingsThemeIndexRouteImport } from './routes/admin/settings/theme/index'
import { Route as AdminSettingsProfileIndexRouteImport } from './routes/admin/settings/profile/index'
import { Route as AdminProductsCategoriesIndexRouteImport } from './routes/admin/products/categories/index'
import { Route as AdminContactsCustomersIndexRouteImport } from './routes/admin/contacts/customers/index'
import { Route as AdminContactsCompaniesIndexRouteImport } from './routes/admin/contacts/companies/index'

const TestRouteRoute = TestRouteRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TestHomeRoute = TestHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => TestRouteRoute,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTransactionsIndexRoute = AdminTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRolesIndexRoute = AdminUsersRolesIndexRouteImport.update({
  id: '/users/roles/',
  path: '/users/roles/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsThemeIndexRoute = AdminSettingsThemeIndexRouteImport.update({
  id: '/theme/',
  path: '/theme/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsProfileIndexRoute =
  AdminSettingsProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminProductsCategoriesIndexRoute =
  AdminProductsCategoriesIndexRouteImport.update({
    id: '/products/categories/',
    path: '/products/categories/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminContactsCustomersIndexRoute =
  AdminContactsCustomersIndexRouteImport.update({
    id: '/contacts/customers/',
    path: '/contacts/customers/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminContactsCompaniesIndexRoute =
  AdminContactsCompaniesIndexRouteImport.update({
    id: '/contacts/companies/',
    path: '/contacts/companies/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/test': typeof TestRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/test/home': typeof TestHomeRoute
  '/admin/': typeof AdminIndexRoute
  '/test/': typeof TestIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/transactions': typeof AdminTransactionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/admin/contacts/companies': typeof AdminContactsCompaniesIndexRoute
  '/admin/contacts/customers': typeof AdminContactsCustomersIndexRoute
  '/admin/products/categories': typeof AdminProductsCategoriesIndexRoute
  '/admin/settings/profile': typeof AdminSettingsProfileIndexRoute
  '/admin/settings/theme': typeof AdminSettingsThemeIndexRoute
  '/admin/users/roles': typeof AdminUsersRolesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test/home': typeof TestHomeRoute
  '/admin': typeof AdminIndexRoute
  '/test': typeof TestIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/transactions': typeof AdminTransactionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/admin/contacts/companies': typeof AdminContactsCompaniesIndexRoute
  '/admin/contacts/customers': typeof AdminContactsCustomersIndexRoute
  '/admin/products/categories': typeof AdminProductsCategoriesIndexRoute
  '/admin/settings/profile': typeof AdminSettingsProfileIndexRoute
  '/admin/settings/theme': typeof AdminSettingsThemeIndexRoute
  '/admin/users/roles': typeof AdminUsersRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/test': typeof TestRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/test/home': typeof TestHomeRoute
  '/admin/': typeof AdminIndexRoute
  '/test/': typeof TestIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/transactions/': typeof AdminTransactionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/admin/contacts/companies/': typeof AdminContactsCompaniesIndexRoute
  '/admin/contacts/customers/': typeof AdminContactsCustomersIndexRoute
  '/admin/products/categories/': typeof AdminProductsCategoriesIndexRoute
  '/admin/settings/profile/': typeof AdminSettingsProfileIndexRoute
  '/admin/settings/theme/': typeof AdminSettingsThemeIndexRoute
  '/admin/users/roles/': typeof AdminUsersRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/test'
    | '/admin/settings'
    | '/test/home'
    | '/admin/'
    | '/test/'
    | '/admin/products'
    | '/admin/settings/'
    | '/admin/transactions'
    | '/admin/users'
    | '/auth/login'
    | '/admin/contacts/companies'
    | '/admin/contacts/customers'
    | '/admin/products/categories'
    | '/admin/settings/profile'
    | '/admin/settings/theme'
    | '/admin/users/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test/home'
    | '/admin'
    | '/test'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/auth/login'
    | '/admin/contacts/companies'
    | '/admin/contacts/customers'
    | '/admin/products/categories'
    | '/admin/settings/profile'
    | '/admin/settings/theme'
    | '/admin/users/roles'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/test'
    | '/admin/settings'
    | '/test/home'
    | '/admin/'
    | '/test/'
    | '/admin/products/'
    | '/admin/settings/'
    | '/admin/transactions/'
    | '/admin/users/'
    | '/auth/login/'
    | '/admin/contacts/companies/'
    | '/admin/contacts/customers/'
    | '/admin/products/categories/'
    | '/admin/settings/profile/'
    | '/admin/settings/theme/'
    | '/admin/users/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  TestRouteRoute: typeof TestRouteRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof TestRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/test/home': {
      id: '/test/home'
      path: '/home'
      fullPath: '/test/home'
      preLoaderRoute: typeof TestHomeRouteImport
      parentRoute: typeof TestRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/transactions/': {
      id: '/admin/transactions/'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/roles/': {
      id: '/admin/users/roles/'
      path: '/users/roles'
      fullPath: '/admin/users/roles'
      preLoaderRoute: typeof AdminUsersRolesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/theme/': {
      id: '/admin/settings/theme/'
      path: '/theme'
      fullPath: '/admin/settings/theme'
      preLoaderRoute: typeof AdminSettingsThemeIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/profile/': {
      id: '/admin/settings/profile/'
      path: '/profile'
      fullPath: '/admin/settings/profile'
      preLoaderRoute: typeof AdminSettingsProfileIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/products/categories/': {
      id: '/admin/products/categories/'
      path: '/products/categories'
      fullPath: '/admin/products/categories'
      preLoaderRoute: typeof AdminProductsCategoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contacts/customers/': {
      id: '/admin/contacts/customers/'
      path: '/contacts/customers'
      fullPath: '/admin/contacts/customers'
      preLoaderRoute: typeof AdminContactsCustomersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contacts/companies/': {
      id: '/admin/contacts/companies/'
      path: '/contacts/companies'
      fullPath: '/admin/contacts/companies'
      preLoaderRoute: typeof AdminContactsCompaniesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminSettingsRouteRouteChildren {
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminSettingsProfileIndexRoute: typeof AdminSettingsProfileIndexRoute
  AdminSettingsThemeIndexRoute: typeof AdminSettingsThemeIndexRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminSettingsProfileIndexRoute: AdminSettingsProfileIndexRoute,
  AdminSettingsThemeIndexRoute: AdminSettingsThemeIndexRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminTransactionsIndexRoute: typeof AdminTransactionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminContactsCompaniesIndexRoute: typeof AdminContactsCompaniesIndexRoute
  AdminContactsCustomersIndexRoute: typeof AdminContactsCustomersIndexRoute
  AdminProductsCategoriesIndexRoute: typeof AdminProductsCategoriesIndexRoute
  AdminUsersRolesIndexRoute: typeof AdminUsersRolesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminTransactionsIndexRoute: AdminTransactionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminContactsCompaniesIndexRoute: AdminContactsCompaniesIndexRoute,
  AdminContactsCustomersIndexRoute: AdminContactsCustomersIndexRoute,
  AdminProductsCategoriesIndexRoute: AdminProductsCategoriesIndexRoute,
  AdminUsersRolesIndexRoute: AdminUsersRolesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface TestRouteRouteChildren {
  TestHomeRoute: typeof TestHomeRoute
  TestIndexRoute: typeof TestIndexRoute
}

const TestRouteRouteChildren: TestRouteRouteChildren = {
  TestHomeRoute: TestHomeRoute,
  TestIndexRoute: TestIndexRoute,
}

const TestRouteRouteWithChildren = TestRouteRoute._addFileChildren(
  TestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  TestRouteRoute: TestRouteRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
