/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteRouteImport } from './routes/test/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TestHomeRouteImport } from './routes/test/home'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminContactsUsersIndexRouteImport } from './routes/admin/contacts/users/index'
import { Route as AdminContactsCustomersIndexRouteImport } from './routes/admin/contacts/customers/index'

const TestRouteRoute = TestRouteRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TestHomeRoute = TestHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => TestRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContactsUsersIndexRoute = AdminContactsUsersIndexRouteImport.update({
  id: '/contacts/users/',
  path: '/contacts/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContactsCustomersIndexRoute =
  AdminContactsCustomersIndexRouteImport.update({
    id: '/contacts/customers/',
    path: '/contacts/customers/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/test': typeof TestRouteRouteWithChildren
  '/test/home': typeof TestHomeRoute
  '/admin/': typeof AdminIndexRoute
  '/test/': typeof TestIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/admin/contacts/customers': typeof AdminContactsCustomersIndexRoute
  '/admin/contacts/users': typeof AdminContactsUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test/home': typeof TestHomeRoute
  '/admin': typeof AdminIndexRoute
  '/test': typeof TestIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/admin/contacts/customers': typeof AdminContactsCustomersIndexRoute
  '/admin/contacts/users': typeof AdminContactsUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/test': typeof TestRouteRouteWithChildren
  '/test/home': typeof TestHomeRoute
  '/admin/': typeof AdminIndexRoute
  '/test/': typeof TestIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/admin/contacts/customers/': typeof AdminContactsCustomersIndexRoute
  '/admin/contacts/users/': typeof AdminContactsUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/test'
    | '/test/home'
    | '/admin/'
    | '/test/'
    | '/admin/products'
    | '/auth/login'
    | '/admin/contacts/customers'
    | '/admin/contacts/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test/home'
    | '/admin'
    | '/test'
    | '/admin/products'
    | '/auth/login'
    | '/admin/contacts/customers'
    | '/admin/contacts/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/test'
    | '/test/home'
    | '/admin/'
    | '/test/'
    | '/admin/products/'
    | '/auth/login/'
    | '/admin/contacts/customers/'
    | '/admin/contacts/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  TestRouteRoute: typeof TestRouteRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof TestRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/test/home': {
      id: '/test/home'
      path: '/home'
      fullPath: '/test/home'
      preLoaderRoute: typeof TestHomeRouteImport
      parentRoute: typeof TestRouteRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contacts/users/': {
      id: '/admin/contacts/users/'
      path: '/contacts/users'
      fullPath: '/admin/contacts/users'
      preLoaderRoute: typeof AdminContactsUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contacts/customers/': {
      id: '/admin/contacts/customers/'
      path: '/contacts/customers'
      fullPath: '/admin/contacts/customers'
      preLoaderRoute: typeof AdminContactsCustomersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminContactsCustomersIndexRoute: typeof AdminContactsCustomersIndexRoute
  AdminContactsUsersIndexRoute: typeof AdminContactsUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminContactsCustomersIndexRoute: AdminContactsCustomersIndexRoute,
  AdminContactsUsersIndexRoute: AdminContactsUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface TestRouteRouteChildren {
  TestHomeRoute: typeof TestHomeRoute
  TestIndexRoute: typeof TestIndexRoute
}

const TestRouteRouteChildren: TestRouteRouteChildren = {
  TestHomeRoute: TestHomeRoute,
  TestIndexRoute: TestIndexRoute,
}

const TestRouteRouteWithChildren = TestRouteRoute._addFileChildren(
  TestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  TestRouteRoute: TestRouteRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
